gtitle:             Clean Blog
email:             syahrulfadli2019@gmail.com
description:       A Blog Theme by Start Bootstrap
author:            Start Bootstrap
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "https://kamvretterbang.github.io"

# Social Profiles
twitter_username:  syahrul110100
github_username:   kamvretterbang
facebook_username: syahrul.fadly.52

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
