title:             Syahrul Fadli
email:             syahrul2019@gmail.com
description:       Personal Blog
author:            Syahrul
baseurl:           "/"
url:               "https://kamvretterbang.github.io"

# Social Profiles
twitter_username:  syahrul110100
github_username:   kamvretterbang
facebook_username: syahrul.fadly.52

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
